DATABASE_URL = "mysql+pymysql://root:Oneserver%401234@localhost/document_db"
SECRET_KEY = "your_secret_key"
ALGORITHM = "HS256"
SENDER_EMAIL = "patilatharva1214@gmail.com"
APP_PASSWORD = "aqpa iekp mcrb ctdr"
